name: lingola_app
description: "Live Lingola Application"
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  rive: ^0.13.0
  flutter_svg: ^2.0.10
  lottie: ^3.0.0
  image_picker: ^1.1.2
  flutter_secure_storage: any
  flutter_facebook_auth: any
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.3.0 # Sürüm çakışmasını çözmek için güncellendi
  google_sign_in: ^6.2.2
  http: ^1.2.2
  firebase_core: ^3.6.0 # Sürüm çakışmasını çözmek için güncellendi
  onesignal_flutter: ^5.4.1
  purchases_flutter: ^9.14.0
  purchases_ui_flutter: ^9.14.0
  speech_to_text: ^6.6.0
  flutter_tts: ^4.2.5
  intl: ^0.19.0
  firebase_storage: ^12.4.5
  package_info_plus: ^8.0.2

dependency_overrides:
  win32: 5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo/live_lingola_logo.png
    - assets/fonts/
    - assets/images/onboarding/
    - assets/images/onboarding/flags/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/
    - assets/images/icons/features/
    - assets/images/icons/actions/
    - assets/images/icons/notifications/
    - assets/images/icons/nav/
    - assets/images/onboarding1/
    - assets/images/flags/
    - assets/images/notificationspage/
    - assets/images/logout/
    - assets/images/icons/translate/
    - assets/images/ProfileSettings/
    - assets/images/PhotoTranslate/
    - assets/images/demo/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/live_lingola_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/live_lingola_logo.png"
