// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrdo5xFcxHI_yEJuqXaCxGCZGWs1FjxE',
    appId: '1:479984027693:web:debaebf97b910c55a290a4',
    messagingSenderId: '479984027693',
    projectId: 'live-lingola',
    authDomain: 'live-lingola.firebaseapp.com',
    storageBucket: 'live-lingola.firebasestorage.app',
    measurementId: 'G-R30YFN4LX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvk33LxYHkwaovAM3vZgMpMvZgfpwJAw',
    appId: '1:479984027693:android:3543ed810d99e7cea290a4',
    messagingSenderId: '479984027693',
    projectId: 'live-lingola',
    storageBucket: 'live-lingola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSDvtxk1vGWCNa6SGdYONpZ3F_ad_Ze4',
    appId: '1:479984027693:ios:b9574514e5aa123ea290a4',
    messagingSenderId: '479984027693',
    projectId: 'live-lingola',
    storageBucket: 'live-lingola.firebasestorage.app',
    iosClientId:
        '479984027693-sk1rqp1qk2laktpj786otccm4ef6rtv7.apps.googleusercontent.com',
    iosBundleId: 'com.flywork.livelingolaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSDvtxk1vGWCNa6SGdYONpZ3F_ad_Ze4',
    appId: '1:479984027693:ios:65d2ecfd877ded12a290a4',
    messagingSenderId: '479984027693',
    projectId: 'live-lingola',
    storageBucket: 'live-lingola.firebasestorage.app',
    iosClientId:
        '479984027693-l703ot47orm9unh8ssasbgqn7a739a3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lingoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrdo5xFcxHI_yEJuqXaCxGCZGWs1FjxE',
    appId: '1:479984027693:web:6408aaf61f93cc2ca290a4',
    messagingSenderId: '479984027693',
    projectId: 'live-lingola',
    authDomain: 'live-lingola.firebaseapp.com',
    storageBucket: 'live-lingola.firebasestorage.app',
    measurementId: 'G-53QDP4C9FJ',
  );
}
